package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button; 
import javafx.scene.control.Label; 
import javafx.scene.control.TextField;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;

import javafx.event.ActionEvent;

import javafx.event.ActionEvent;

public class mainMenuController {

	// Event Listener on Button.onAction
	public void Back(ActionEvent event) {
		// TODO Autogenerated
		Main m = new Main(); 
		m.changeScene("/application/loginScene.fxml");
	}
	@FXML
	private Label welcomename; 
	
	@FXML
	public void EffortLogger(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void PokerProcess(ActionEvent event) {
		Main m = new Main(); 
		m.changeScene("/application/pokerProcessEmployee.fxml");
	}
	
	/*
	 * 
	 * To be implemented later cause JavaFX is weird 
	public void changeName(String name_arg) {
		welcomename.setText("Welcome " + name_arg);
	}
	*/
}
